### ISSUE TITLE
Yammer URL redirects to 1.3.1 instead of 1.3.2

### ISSUE THREAD

**Issue by lashomb** [autopkg/jlehikoinen-recipes#1]
Looks like the download URL might be a manual redirect by Microsoft.

URL for 1.3.2 is same construct as 1.3.1, which is https://yammerdesktopapp.blob.core.windows.net/binaries/dist/darwin/x64/1.3.2/Yammer-1.3.2.dmg

Might need to rebuild this on that URL structure rather than the aka.ms redirect.

**Comment by jlehikoinen** [comment]
Hi!

Thanks for noticing this. Do you know when was this 1.3.2 version released? I've found out that some of the MS AutoPkg recipes are few days late because of MS CDNs.

I believe it's relatively difficult to scrape that redirected path for newer versions? Or do you have some  way of doing that?

**Comment by jlehikoinen** [comment]
Seems that Yammer has been updated since and the recipe download URL still works. Last version I checked was 2.0.1.
