### ISSUE TITLE
Curl failure: Failed to connect to sb224.sbweb.microsoft.com port 443: Connection refused (exit code 7)

### ISSUE THREAD

**Issue by macmule** [autopkg/jlehikoinen-recipes#2]
Could be down, https://sb224.sbweb.microsoft.com is not happy.

Logging incase someone else has the issue & in case a temp issue.

**Comment by jlehikoinen** [comment]
Ouch, so it seems. Do you know where to find a "generic" Microsoft meeting URL? Usually the meeting URLs and download links are company specific.

I believe they're gradually moving towards using the new "Skype Meetings App". I'll create a download recipe for this today.

**Comment by jlehikoinen** [comment]
Download URL `https://sb224.sbweb.microsoft.com//lwa/Plugins/SkypeForBusinessPlugin.pkg` seems to be working again.
