### ISSUE TITLE
SkypeForBusinessWebApp.download.recipe fails with a 404 error

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/jlehikoinen-recipes#3]
Looks like the URL coded into the recipe (https://sb224.sbweb.microsoft.com//lwa/Plugins/SkypeForBusinessPlugin.pkg) now 404's.
```
The following recipes failed:
    SkypeForBusinessWebApp.download.recipe
        Error in com.github.jlehikoinen.download.SkypeForBusinessWebApp: Processor: URLDownloader: Error: Curl failure: Could not resolve host: sb224.sbweb.microsoft.com (exit code 6)
```
Do you have any details on how you grabbed this URL originally? 

Thanks

**Comment by Daz-wallace** [comment]
Bump 😊

**Comment by jlehikoinen** [comment]
Currently on vacation. Will look into this in few weeks..

Can't remember where I found that URL. :)

**Comment by Daz-wallace** [comment]
No worries at all. Have a great one!

**Comment by jlehikoinen** [comment]
Thanks! It was great. :)

Running into dead-ends here. I don't have access to any orgs that still use Skype Meetings App or Skype for Business Web App. If you know one you could dig that download URL joining Skype for Business meeting via browser? Then you'd need your own custom download recipe using that org's download url.

Some related info here:

https://support.office.com/en-us/article/join-a-skype-for-business-meeting-with-skype-meetings-app-skype-for-business-web-app-4828ad18-ed21-422a-a870-94d676d4b72a

Seems they are EOLing Skype Meetings App (and probably Skype for Business Web App):

"If you previously installed Skype Meetings App to join a Skype for Business meeting, you can install the desktop app now. Skype Meetings App will no longer be used for meetings on Mac."

https://support.office.com/en-us/article/join-meetings-with-skype-for-business-desktop-client-for-mac-2cf0517a-2f7d-4c9d-9824-e0f3c61d0040?ui=en-US&rs=en-US&ad=US
