### ISSUE TITLE
Sibelius.munki.recipe not copying to munki

### ISSUE THREAD

**Issue by ewtillman** [autopkg/jlehikoinen-recipes#5]
Looks like it downloads the sibelius pkg fine but is not copying the required files over to munki.

**Comment by jlehikoinen** [comment]
Sibelius.download recipe downloads dmg containing quite old package (Install Sibelius 7.5.1.pkg) which has expired code signing certificate (14th of April 2017).

The recipe should work fine if you disable code signature verification:
`$ autopkg run -v -k DISABLE_CODE_SIGNATURE_VERIFICATION=1 Sibelius.munki`
